include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - ios/**
    - android/**

linter:
  rules:
    # Mantenerlo simple: queremos calidad, pero sin volver el build frágil.
    avoid_print: false
