workflows:
  android-apk:
    name: Android Release (APK + AAB) - GaBoLP
    max_build_duration: 60
    environment:
      flutter: stable

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper

    scripts:
      - name: Preparar proyecto (crear android si falta)
        script: |
          set -e
          if [ ! -d "android" ]; then
            TMPDIR="$(mktemp -d)"
            cp -R lib "$TMPDIR/lib"
            if [ -d "assets" ]; then cp -R assets "$TMPDIR/assets"; fi
            cp pubspec.yaml "$TMPDIR/pubspec.yaml"

            flutter create . --platforms=android --org com.gabolp.app

            rm -f pubspec.yaml
            cp "$TMPDIR/pubspec.yaml" pubspec.yaml

            rm -rf lib
            cp -R "$TMPDIR/lib" lib

            if [ -d "$TMPDIR/assets" ]; then
              rm -rf assets
              cp -R "$TMPDIR/assets" assets
            fi
          fi

      - name: Forzar permisos INTERNET + CAMERA en AndroidManifest MAIN
        script: |
          set -e
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          echo "Usando: $MANIFEST"
          if [ ! -f "$MANIFEST" ]; then
            echo "ERROR: No existe $MANIFEST"
            echo "Manifests encontrados:"
            find android -name AndroidManifest.xml -print || true
            exit 1
          fi

          insert_perm () {
            local PERM="$1"
            if grep -q "$PERM" "$MANIFEST"; then
              echo "$PERM ya estaba en el MAIN manifest."
            else
              echo "Insertando $PERM en el MAIN manifest..."
              perl -0777 -i -pe "s/(<manifest[^>]*>)/\$1\n    <uses-permission android:name=\"$PERM\"\/>/s" "$MANIFEST"
            fi
          }

          insert_feature () {
            local FEATURE="$1"
            if grep -q "$FEATURE" "$MANIFEST"; then
              echo "$FEATURE ya estaba en el MAIN manifest."
            else
              echo "Insertando uses-feature $FEATURE..."
              perl -0777 -i -pe "s/(<manifest[^>]*>)/\$1\n    <uses-feature android:name=\"$FEATURE\" android:required=\"false\"\/>/s" "$MANIFEST"
            fi
          }

          insert_perm "android.permission.INTERNET"
          insert_perm "android.permission.CAMERA"
          insert_feature "android.hardware.camera"

          echo "Chequeo MAIN manifest:"
          grep -n "android.permission.INTERNET" "$MANIFEST" || true
          grep -n "android.permission.CAMERA" "$MANIFEST" || true
          head -n 30 "$MANIFEST"

      - name: Fix ML Kit OCR (R8) - agregar módulos de reconocimiento de texto
        script: |
          set -e

          # google_mlkit_text_recognition referencia clases de opciones para otros alfabetos.
          # En builds release con R8/minify, si esos artefactos no están, falla con
          # "Missing class ...TextRecognizerOptions".

          # Patch para build.gradle (Groovy)
          GRADLE_FILE="android/app/build.gradle"
          if [ -f "$GRADLE_FILE" ]; then
            if ! grep -q "text-recognition-korean" "$GRADLE_FILE"; then
              echo "Parchando $GRADLE_FILE con dependencias ML Kit adicionales..."
              perl -0777 -i -pe 's/(dependencies\s*\{)/$1\n    implementation "com.google.mlkit:text-recognition-chinese:16.0.0"\n    implementation "com.google.mlkit:text-recognition-japanese:16.0.0"\n    implementation "com.google.mlkit:text-recognition-korean:16.0.0"\n    implementation "com.google.mlkit:text-recognition-devanagari:16.0.0"\n/s' "$GRADLE_FILE"
            else
              echo "Dependencias ML Kit ya estaban presentes en $GRADLE_FILE"
            fi
          fi

          # Patch para build.gradle.kts (por si cambia el template)
          GRADLE_KTS_FILE="android/app/build.gradle.kts"
          if [ -f "$GRADLE_KTS_FILE" ]; then
            if ! grep -q "text-recognition-korean" "$GRADLE_KTS_FILE"; then
              echo "Parchando $GRADLE_KTS_FILE con dependencias ML Kit adicionales..."
              perl -0777 -i -pe 's/(dependencies\s*\{)/$1\n    implementation("com.google.mlkit:text-recognition-chinese:16.0.0")\n    implementation("com.google.mlkit:text-recognition-japanese:16.0.0")\n    implementation("com.google.mlkit:text-recognition-korean:16.0.0")\n    implementation("com.google.mlkit:text-recognition-devanagari:16.0.0")\n/s' "$GRADLE_KTS_FILE"
            else
              echo "Dependencias ML Kit ya estaban presentes en $GRADLE_KTS_FILE"
            fi
          fi

          # Proguard keep rules (si minify está activado)
          PROGUARD_FILE="android/app/proguard-rules.pro"
          if [ -f "$PROGUARD_FILE" ]; then
            if ! grep -q "ML Kit text recognition" "$PROGUARD_FILE"; then
              echo "Agregando reglas Proguard para ML Kit en $PROGUARD_FILE"
              cat >> "$PROGUARD_FILE" <<'EOF'

# ML Kit text recognition (google_mlkit_text_recognition)
-keep class com.google.mlkit.vision.text.** { *; }
-dontwarn com.google.mlkit.vision.text.**
EOF
            fi
          fi

      - name: Instalar dependencias
        script: |
          flutter pub get

      - name: Generar ícono de la app
        script: |
          set -e
          dart run flutter_launcher_icons

      - name: Generar Splash
        script: |
          flutter pub run flutter_native_splash:create

      - name: Compilar APK Release
        script: |
          flutter build apk --release --build-number=${BUILD_NUMBER:-1}
          flutter build appbundle --release --build-number=${BUILD_NUMBER:-1}


      - name: Verificar INTERNET en merged manifest final (build/app)
        script: |
          set -e
          echo "Buscando merged manifest de la APP..."
          find build/app -path "*merged_manifests*" -name "AndroidManifest.xml" -print || true
          MERGED="$(find build/app -path "*merged_manifests*" -path "*release*" -name "AndroidManifest.xml" | head -n 1)"
          echo "MERGED=$MERGED"

          if [ -z "$MERGED" ]; then
            echo "No encontré el merged manifest de la app (build/app)."
            exit 1
          fi

          if grep -q "android.permission.INTERNET" "$MERGED"; then
            echo "OK ✅ El merged manifest de la APP tiene INTERNET."
          else
            echo "ERROR ❌ El merged manifest de la APP NO tiene INTERNET."
            head -n 120 "$MERGED"
            exit 1
          fi


    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
          
