workflows:
  android-apk:
    name: Android APK - GaBoLP
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Preparar proyecto (crear android si falta)
        script: |
          set -e

          if [ ! -d "android" ]; then
            TMPDIR="$(mktemp -d)"
            cp -R lib "$TMPDIR/lib"
            if [ -d "assets" ]; then cp -R assets "$TMPDIR/assets"; fi
            cp pubspec.yaml "$TMPDIR/pubspec.yaml"

            flutter create . --platforms=android --org com.gabolp.app

            rm -f pubspec.yaml
            cp "$TMPDIR/pubspec.yaml" pubspec.yaml

            rm -rf lib
            cp -R "$TMPDIR/lib" lib

            if [ -d "$TMPDIR/assets" ]; then
              rm -rf assets
              cp -R "$TMPDIR/assets" assets
            fi
          fi

      - name: Instalar dependencias
        script: |
          flutter pub get

      - name: Asegurar permiso INTERNET en AndroidManifest
        script: |
          set -e
          MANIFEST="android/app/src/main/AndroidManifest.xml"

          if [ ! -f "$MANIFEST" ]; then
            echo "ERROR: No se encontró $MANIFEST"
            exit 1
          fi

          if grep -q "android.permission.INTERNET" "$MANIFEST"; then
            echo "OK: INTERNET ya estaba en el manifest."
          else
            echo "Insertando INTERNET en el manifest..."
            perl -0777 -i -pe 's@(<manifest[^>]*>)@$1\n    <uses-permission android:name="android.permission.INTERNET"/>@s' "$MANIFEST"
          fi

          echo "Manifest (primeras 80 líneas):"
          head -n 80 "$MANIFEST"

      - name: Build APK (release)
        script: |
          flutter build apk --release

      - name: Verificar que el Manifest final (merged) tenga INTERNET
        script: |
          set -e
          echo "Buscando merged manifest de la APP..."
          MERGED="$(find build/app -path "*merged_manifests*" -path "*release*" -name "AndroidManifest.xml" | head -n 1)"
          echo "MERGED=$MERGED"

          if [ -z "$MERGED" ]; then
            echo "ERROR: No se encontró merged manifest."
            exit 1
          fi

          if grep -q "android.permission.INTERNET" "$MERGED"; then
            echo "OK ✅ El merged manifest de la APP tiene INTERNET."
          else
            echo "ERROR ❌ El merged manifest de la APP NO tiene INTERNET."
            head -n 160 "$MERGED"
            exit 1
          fi

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
