workflows:
  android-apk:
    name: Android Release (APK + AAB) - GaBoLP
    max_build_duration: 60
    environment:
      flutter: stable

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper

    scripts:
      - name: Preparar proyecto (crear android si falta)
        script: |
          set -e
          if [ ! -d "android" ]; then
            TMPDIR="$(mktemp -d)"
            cp -R lib "$TMPDIR/lib"
            if [ -d "assets" ]; then cp -R assets "$TMPDIR/assets"; fi
            cp pubspec.yaml "$TMPDIR/pubspec.yaml"

            flutter create . --platforms=android --org com.gabolp.app

            rm -f pubspec.yaml
            cp "$TMPDIR/pubspec.yaml" pubspec.yaml

            rm -rf lib
            cp -R "$TMPDIR/lib" lib

            if [ -d "$TMPDIR/assets" ]; then
              rm -rf assets
              cp -R "$TMPDIR/assets" assets
            fi
          fi

      - name: Forzar permisos INTERNET + CAMERA en AndroidManifest MAIN
        script: |
          set -e
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          echo "Usando: $MANIFEST"
          if [ ! -f "$MANIFEST" ]; then
            echo "ERROR: No existe $MANIFEST"
            echo "Manifests encontrados:"
            find android -name AndroidManifest.xml -print || true
            exit 1
          fi

          insert_perm () {
            local PERM="$1"
            if grep -q "$PERM" "$MANIFEST"; then
              echo "$PERM ya estaba en el MAIN manifest."
            else
              echo "Insertando $PERM en el MAIN manifest..."
              perl -0777 -i -pe "s/(<manifest[^>]*>)/\$1\n    <uses-permission android:name=\"$PERM\"\/>/s" "$MANIFEST"
            fi
          }

          insert_feature () {
            local FEATURE="$1"
            if grep -q "$FEATURE" "$MANIFEST"; then
              echo "$FEATURE ya estaba en el MAIN manifest."
            else
              echo "Insertando uses-feature $FEATURE..."
              perl -0777 -i -pe "s/(<manifest[^>]*>)/\$1\n    <uses-feature android:name=\"$FEATURE\" android:required=\"false\"\/>/s" "$MANIFEST"
            fi
          }

          insert_perm "android.permission.INTERNET"
          insert_perm "android.permission.CAMERA"
          insert_perm "android.permission.RECORD_AUDIO"
          insert_feature "android.hardware.camera"

          echo "Chequeo MAIN manifest:"
          grep -n "android.permission.INTERNET" "$MANIFEST" || true
          grep -n "android.permission.CAMERA" "$MANIFEST" || true
          head -n 30 "$MANIFEST"

      - name: Fix ML Kit OCR (R8) - evitar Missing classes
        script: |
          set -e

          # google_mlkit_text_recognition referencia opciones para varios alfabetos.
          # En release con R8, si esos módulos no están, puede fallar con "Missing class ...TextRecognizerOptions".
          # Solución robusta y simple: agregar los artefactos ML Kit faltantes.

          python3 - <<'PY'
          from pathlib import Path
          import re

          KTS_DEPS = [
              'implementation("com.google.mlkit:text-recognition-chinese:16.0.0")',
              'implementation("com.google.mlkit:text-recognition-japanese:16.0.0")',
              'implementation("com.google.mlkit:text-recognition-korean:16.0.0")',
              'implementation("com.google.mlkit:text-recognition-devanagari:16.0.0")',
          ]

          GROOVY_DEPS = [
              "implementation 'com.google.mlkit:text-recognition-chinese:16.0.0'",
              "implementation 'com.google.mlkit:text-recognition-japanese:16.0.0'",
              "implementation 'com.google.mlkit:text-recognition-korean:16.0.0'",
              "implementation 'com.google.mlkit:text-recognition-devanagari:16.0.0'",
          ]

          def insert_after_dependencies_open(s: str, lines: list[str], indent: str) -> str:
              if 'text-recognition-korean' in s:
                  return s
              pat = re.compile(r"(^\s*dependencies\s*\{\s*$)", re.M)
              m = pat.search(s)
              if not m:
                  return s
              insert = "\n" + "\n".join([indent + ln for ln in lines]) + "\n"
              return s[:m.end()] + insert + s[m.end():]

          kts = Path('android/app/build.gradle.kts')
          groovy = Path('android/app/build.gradle')

          if kts.exists():
              s = kts.read_text(encoding='utf-8')
              s = insert_after_dependencies_open(s, KTS_DEPS, indent='        ')
              kts.write_text(s, encoding='utf-8')
              print('OK: patched build.gradle.kts (deps)')
          elif groovy.exists():
              s = groovy.read_text(encoding='utf-8')
              s = insert_after_dependencies_open(s, GROOVY_DEPS, indent='    ')
              groovy.write_text(s, encoding='utf-8')
              print('OK: patched build.gradle (deps)')
          else:
              print('WARN: no app gradle file found')
          PY

          # Suprimir warnings si R8/Proguard los muestra por módulos opcionales
          PROGUARD_FILE="android/app/proguard-rules.pro"
          mkdir -p "$(dirname "$PROGUARD_FILE")"
          touch "$PROGUARD_FILE"
          if ! grep -q "MLKIT_TEXT_RECOGNITION_R8" "$PROGUARD_FILE"; then
            printf '%s\n' \
              '# MLKIT_TEXT_RECOGNITION_R8' \
              '-dontwarn com.google.mlkit.vision.text.chinese.**' \
              '-dontwarn com.google.mlkit.vision.text.japanese.**' \
              '-dontwarn com.google.mlkit.vision.text.korean.**' \
              '-dontwarn com.google.mlkit.vision.text.devanagari.**' \
              >> "$PROGUARD_FILE"
          fi
      - name: Instalar dependencias
        script: |
          flutter pub get

      - name: Analizar código (detecta errores antes del build)
        script: |
          # No fallar por 'info' y 'warning' (solo por errores reales).
          flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Fix plugin record (AGP 8+) - agregar namespace
        script: |
          set -e
          echo "Buscando 'record-*' en pub-cache..."

          # En AGP 8+ todos los módulos Android necesitan 'namespace' en build.gradle.
          # La versión record 4.4.4 no lo trae y rompe builds release.
          # Parcheamos el build.gradle del plugin en pub-cache usando el 'package' del AndroidManifest.xml.
          REC_DIR="$(find "$HOME/.pub-cache/hosted" -maxdepth 2 -type d -name "record-*" 2>/dev/null | head -n 1)"

          if [ -z "$REC_DIR" ]; then
            echo "WARN: No encontré record-* en pub-cache (¿se instaló record?)."
            exit 0
          fi

          GRADLE_FILE="$REC_DIR/android/build.gradle"
          MANIFEST_FILE="$REC_DIR/android/src/main/AndroidManifest.xml"

          if [ ! -f "$GRADLE_FILE" ]; then
            echo "WARN: No existe $GRADLE_FILE"
            exit 0
          fi

          if grep -q "namespace" "$GRADLE_FILE"; then
            echo "OK: record ya tiene namespace."
            exit 0
          fi

          NS=""
          if [ -f "$MANIFEST_FILE" ]; then
            NS="$(grep -oE 'package="[^"]+"' "$MANIFEST_FILE" | head -n 1 | sed 's/package="//;s/"//')"
          fi

          if [ -z "$NS" ]; then
            NS="com.llfbandit.record"
          fi

          echo "Parchando record namespace=$NS en $GRADLE_FILE"
          perl -0777 -i -pe "s/android\s*\{/android {\n    namespace \\\"$NS\\\"/s" "$GRADLE_FILE"

      - name: Generar ícono de la app
        script: |
          set -e
          dart run flutter_launcher_icons

      - name: Generar Splash
        script: |
          flutter pub run flutter_native_splash:create

      - name: Compilar APK Release
        script: |
          flutter build apk --release --build-number=${BUILD_NUMBER:-1}
          flutter build appbundle --release --build-number=${BUILD_NUMBER:-1}


      - name: Verificar INTERNET en merged manifest final (build/app)
        script: |
          set -e
          echo "Buscando merged manifest de la APP..."
          find build/app -path "*merged_manifests*" -name "AndroidManifest.xml" -print || true
          MERGED="$(find build/app -path "*merged_manifests*" -path "*release*" -name "AndroidManifest.xml" | head -n 1)"
          echo "MERGED=$MERGED"

          if [ -z "$MERGED" ]; then
            echo "No encontré el merged manifest de la app (build/app)."
            exit 1
          fi

          if grep -q "android.permission.INTERNET" "$MERGED"; then
            echo "OK ✅ El merged manifest de la APP tiene INTERNET."
          else
            echo "ERROR ❌ El merged manifest de la APP NO tiene INTERNET."
            head -n 120 "$MERGED"
            exit 1
          fi


    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
          
